### ISSUE TITLE
Thoughts on Improving Searching

### ISSUE THREAD

**Issue by stevekinney** [skuhlmann/jetfuel#8]
Rather than adding a `.hidden` class to the elements, what about just using jQuery's `.hide()` method?

One thing you might want to consider in `search.js` is to just hide all of them and then show the URLs that match the search criteria. Typically, this will happen before a DOM repaint, so you won't see a flash of crazy or anything like that.

``` js
$('tbody tr').hide()
$('.hide:contains('+searchText+')').show();
```

I might also use a `filter` instead of a complicated selector (which are typically slower).

``` js
$('tbody tr').hide().filter(function (index, element) {
    return !!(element.innerHTML.match(searchText));
  }).show();
```

**Comment by skuhlmann** [comment]
I applied this. Thanks.
